# Generated by Django 3.2 on 2021-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
